---
title: "Group Assignment"
format: html
editor: visual
---

## Overview

As with the individual assignment, you are again taking on the role of Director of the Parks Department for Stratton Parks and you are again being directed by the County Executive to cut the budget by 10%. However, this time, you and your team are expected to prepare a complete report that provides the County Executive 3 alternative plans for cuts, an comparitive analysis of the 3 plans, and a final recommendation. You will draw on the same [Stratton County case](stratton.qmd) case details to inform and prepare your report. **For this assignment, you will prepare a report of no more than 20 pages providing background research on effectively managing budget cuts, preparing 3 budget proposals to accommodate the needed cuts, preparing a stakeholder analysis and engagement plan for each proposal, conducting a comparitive analysis, and making a final recommendation. The report and a video presentation summarizing the report will be due by May 4th, 2023.**

::: callout-note
A reminder that by law, the County Executive must submit his or her budget recommendation to the County Legislature by August 15th, for review (including at least one public hearing) and adoption prior to the start of the new fiscal year on September 1st.
:::

## Details

This section lays out the sections that should be included in your 20 page (or less) report plus a one-page executive summary, in order, with details on expectations for each section. Overall, the format should use APA citation formatting (for both in-text citations and references list), 12-point Times New Roman font, and single-spaced. The first page should be a cover sheet with a title and all group member names clearly printed.

### Executive Summary

This section does not count toward your page count. The report must include a 1-page, single-spaced summary of the full report. The summary should lay out the problem, guiding principles for the solution, the three alternative approaches considered, and finally, the final recommendation. Be clear and concise.

::: callout-note
Many students find summarizing their extended research in a limited space challenging, but such summarizing is an important skill to build. A big part of being prepared in a professional role is doing all the work to get to your answer, knowing how you got to your answer well enough to answer clarifying questions, and identifying for yourself and others what is truly important for making a particular decision. Remember that in this context, there's a full report detailing your process and thinking that will follow the summary; it's okay for the summary to leave details out to get to the bottom-line points.
:::

### Introduction

A 1-2 page introduction that should resemble the executive summary, but with added details on how you approached the problem and how the remainder of the report is structured. A good introduction should provide readers a clear understanding of how you are defining the problem, how you are proposing to resolve the problem, how you are weighing solutions, and the process by which you analyzed your options. Note that professional reports are not mystery novels - readers should know your final conclusion by the end of the introduction.

### Background and Related Research

A 4-6 page summary of research that informs your decision-making. Your research should center on what the evidence says about managing cutbacks and budget reductions, what has been successful in similar cases in other areas, and any evidence that informs the approach(es) you are using in your management of the cutbacks. Do not quote articles or materials directly. Instead, summarize the literature in your own words with citations to works appropriately placed throughout the text.

::: callout-tip
#### Tip - Research Basics

A good approach to doing the background research is to create a list of broad, general search terms that inform the basic themes of what you are doing (in this case, "budget cuts," "cutback management," "contracting," "layoffs," and "collective bargaining agreements" are all reasonable potential starting terms). Once you have your list, use it to search in premier academic journals on the topics ([JPAM](https://onlinelibrary.wiley.com/journal/15206688), [PAR](https://onlinelibrary.wiley.com/journal/15406210?utm_source=google&utm_medium=paidsearch&utm_campaign=R3MR425&utm_content=SocBehavSci&gclid=Cj0KCQiA0oagBhDHARIsAI-BbgdO4YOy7YBp0Ck17cN2y3dYHzVt3pWCPYXVXD6zBiT-22FbfgNekEkaAglEEALw_wcB), [JPART](https://academic.oup.com/jpart), [ROPPA](https://journals.sagepub.com/home/rop), [APSR](https://www.cambridge.org/core/journals/american-political-science-review) and [PMR](https://www.tandfonline.com/journals/rpxm20) are good outlets for this assignment) and in GAO, CRS, and CBO reports to cast a wide net of potential information. I recommend searching directly at the journal's websites or, in [GoogleScholar](https://scholar.google.com), type the search term then add source:"Journal Title" to the search. I recommend using year filters in Google Scholar to get both older and newer research on the subject. Read the abstracts and executive summaries to think about even a loose fit with what you are doing to narrow the number of papers to what's most relevant. Now you have a collection of literature to draw on for informing your background section.
:::

### Proposals Considered

This section will include subsections for each of the three alternative proposals for dealing with the cuts that were analyzed and considered by your team. Each proposal should be 3-4 pages and should include 1) an overview and justification of the plan, 2) a short overview of the cuts, 3) a stakeholder analysis of those affected, and 4) a timeline and plan for engaging stakeholders. You may use no more than 3 tables, in text, in each proposal subsection. Tables should fit on one page, include a title above them, and be discussed in the text to aid reader understanding and complement the proposal narrative.

::: callout-note
Each of you has completed an individual assignment that largely reflected the pieces required of the alternative proposals section. Unless all of you have taken the exact same approach in your individual assignments, it is entirely appropriate and encouraged for you to adopt an edited, polished, and more concise version of your individual assignment as subsections here. You will want to not only revise for space constraints, but also revise for tone, voice, and narrative flow with the rest of the report. You may also, through discussion with one another, make tweaks to the plan.
:::

### Analysis of the Trade-offs and Recommendation

The final section will be a 3-5 page analysis of the three plans in terms of efficiency, effectiveness, equity, and political impact of each plan leading to your final recommendation. As with the background and related research section, this section should include some research on how to define and measure these dimensions of each plan and anchor your recommendation in how each plan compares on these four dimensions. In the introduction, the goals and priorities driving your management of the parks department (and thereby influencing your budgetary priorities) should have been articulated clearly and will help you gauge each proposed alternative budget plan against those goals and priorities.

## Roles and Responsibilities

As with any team project, it is helpful to have clear roles and responsibilities in completing the project. Below is a table of roles and responsibilities that each group will need to assign. Each group should plan on exchanging individual assignments with one another to inform group discussion on which plans (or pieces of plans) should be incorporated as part of the three alternative proposals considered in the assignment. I also highly recommend groups assigning the editing role to who they believe to be a strong writer in the group.

|                    Role                     |                                                                                      Responsibility                                                                                       |
|:-------------------------------:|:-------------------------------------:|
| Introduction, Executive Summary, and Editor | Write the Executive Summary and Introduction. <br/> Suggest edits and revisions to other sections strictly for flow and cohesion. <br/> Edit and provide one of the three proposed plans. |
|       Background and Related Research       |                                 Write the background and related research section. <br/> Edit and provide one of the three proposed plans (if relevant).                                  |
|         Analysis and Recommendation         |                                   Write the analysis and recommendation section. <br/> Edit and provide one of the three proposed plans (if relevant).                                    |
|              One Proposed Plan              |                   Edit and provide on of the three proposed plans. <br/> Aid with finding and organizing background research for the background and analysis sections.                    |

::: callout-important
As there are only 3 alternative plans needed and groups will have 4 members, one person will have their individual plan excluded. The author of the plan from the individual assignments that the group decides is either too similar to other plans or too different from other collectively decided goals or objectives to be included in the full report should take on either the background section or the analysis section. Thus, "(if relevant)" above suggests that one of these roles may not have an alternative budget plan slated for revision and inclusion in the final report. This should never be taken as a suggestion of quality, but instead one of fit.
:::

Teams should plan to meet to assign roles, sign the [group role contract](contract.pdf), and submit the signed contract on Brightspace by midnight on March 8th.

## Presentation

As groups, you will prepare a 15-minute presentation of your final report. The presentation should be delivered via an unedited recording of a Zoom call with a shared screen for presenting slides. A good presentation should be polished, on time, and should provide a clear overview of 1) the nature of the problem you are facing (the budget cuts) and the priorities you carried into resolving it (guided by your research), 2) the three alternatives you considered, and 3) your analysis of their trade-offs and final recommendation.

You will turn in:

1\. A .MP4 file of the recording (I recommend making a practice video to make sure you know how to download and save the recording as an .MP4)\
2. A .PDF of your slides.

Reminder on good presentation basics:

\- Introduce yourselves briefly at the beginning and give a brief purpose statement of the presentation.\
- Make sure your slides are not overly wordy and provide complementary information that does not distract from your own words as you present\
- Keep on time\
- Practice a few times before the final run\
- Make sure you have polished transitions between slides as a speaker and between speakers\
- Remember you are summarizing in a presentation: not every detail or thought from the final paper needs to be in it

## Peer Evaluation

Peer evaluations are due May 4th by Midnight. Instructions are provided on Brightspace.
