---
title: "Syllabus"
---

# Integrative Capstone

## RPAD 507

👨‍🏫: Stephen Holt, Ph.D.\
📅: Asynchronous Online with Synchronous Check-Ins\
📧: sbholt\@albany.edu\
🏫: Tuesdays and Thursdays from 1:00 pm to 5:00 pm or by appointment - book [here](https://calendly.com/sbholt/30min); in-person in Milne 324 or online in [GatherTown](https://app.gather.town/app/REBbcSYb3BTtxRhY/ussalbany).[^1]\
☎️: 518-442-3309

[^1]: Password is RockCollege. Feel free to also use as a meeting spot with your groups - the rooms are private meeting rooms (this will make sense when you use it) and the space itself has a 25 person capacity.

## Course Description

The mission of the Rockefeller College of Public Affairs and Policy Master of Public Administration (MPA) Program is to develop leaders, managers, and advanced analysts who excel in public service within government and across sectors. The MPA curriculum emphasizes the development of technical and managerial skills toward the responsible and ethical uses of discretion in the pursuit exemplary personal and organizational performance (see [the appendix](syllabus507.qmd#appendix) for a list of the competencies). The MPA's mission and curriculum reflects the faculty's commitment to producing committed and engaged public servants whose actions embody public service ideals.

RPAD 507 "Integrative Capstone" is the culmination of this learning process. As such, during this course, students will apply the competencies, knowledge, and skills they have acquired throughout the program to a semester-long case study project in a fictional setting. Course assignments will require students to synthesize and apply skills and material from across the MPA curriculum, individually and in teams.

### Required Materials

The course materials will all be shared through the course Brightspace and this course site. The materials will generally be assignment instructions and helpful supplemental materials.

### Course Structure

As a capstone class, this class is centered around two primary assignments:

1.  An individual assignment to produce a segment of the analysis for the case study final report.
2.  A group assignment to produce a final report - a section of which will be drawn from the individual assignment.

As with all online courses, there is not a weekly meeting time and your group work will be conducted and coordinated with each other. However, unlike most online courses, this course is ensuring an application and synthesis of program skills and materials. As a result, there are not weekly modules. Instead, when the course transitions to the group assignment (March 1st), groups will be expected to meet with the instructor bi-weekly to provide a progress report on their capstone work. The final report will be developed in segments and the bi-weekly check-ins will ensure groups are on track and receive the advice and instruction they need. Groups will sign-up for 30 minute office hour blocks using the link in the header (or [here](https://calendly.com/sbholt/30min)). For any particular meeting, groups can either designate an attendee to bring the update to office hours and pass on feedback or attend as a group.

## Assignments

### Individual Assignment

As an individual, students will write a 6 page (single spaced, 12 point Times New Roman font) stakeholder analysis based on the case study provided to the class. The assignment should open with a 1 page description of the budgetary decision being made and a 5 page stakeholder assessment of the important stakeholders to engage for the decision to be successful. The individual assignment will be due **February 28th** and details for completing the assignment will be provided on Brightspace and the course site during the first week of classes.

### Group Assignment

The group assignment will have four deliverables: 1) a group roles contract (details will be provided on Brightspace) submitted for instructor review (due **March 8th**); 2) an outline of the group's approach to the case (due **March 20th**); 3) the final case study report (due **May 4th**); and 4) a group final presentation video, which can be done as a recorded Zoom with screenshare for slides and a polished presentation from all members (due **May 4th**).

### Grading

The course grade consists of:

1.  Stakeholder analysis (35%)
2.  Final Report (35%)
    1.  Outline (5%)

    2.  Contract (5%)

    3.  Peer Evaluation (10%)

    4.  Report (15%)
3.  Final Presentation (15%)
4.  Completion of Peer Evaluation (15%)

## Detailed Course Schedule

|     Date     |               Assignment                | Readings |
|:------------:|:---------------------------------------:|:--------:|
|     4/28     |        Stakeholder Analysis Due         |          |
|     3/8      |        Group Roles Contract Due         |          |
|  3/7 or 3/9  |          First Group Check-In           |          |
|     3/20     |    1-page outline of group appraoch     |          |
|  4/4 or 4/6  |          Second Group Check-In          |          |
| 4/18 or 4/20 |          Final Group Check-In           |          |
|     5/4      | Final Report and Final Presentation Due |          |

::: callout-note
**NOTE:** I will be adding materials to both the Brightspace and the Course site on working in groups, delivering presentations, and the expectations for the final report. I will post announcements to the class when such updates and materials are posted.
:::

## Class Policies

-   Public policy is a professional field; therefore, I emphasize professional skills in the classroom and assignments. Professional skills are punctuality, adhering to deadlines, and preparedness.
-   Letters of recommendation. If you are a hard working student and serious about a career in public service, I will be a dedicated advocate for you on the job market and will happily write letters of recommendation on your behalf. There is, however, one condition and one recommendation. The condition: I will not write a letter of recommendation for your while you are in my class. This is because to write a good faith, sincere, and thoughtful recommendation, I will need to be able to consider your work as a whole, and while the class is on-going, my assessment of you will be incomplete. After the semester is over, I am happy to help in any way I can, including writing letters. The recommendation: Make an appointment to visit my office hours at least once over the course of the semester to talk informally about your goals, career interests, and other professional ambitions so I can get a better sense of who you are as individuals. The better I know you, the more effective I can be at writing letters on your behalf and thinking of you when opportunities arise.
-   I have a strict open door policy. If there is anything about the course, the assignments, the grading, the material, class, or anything related to public administration/policy or statistics broadly that you would like to discuss, do not hesitate to visit me during office hours or email me. I can respond via email, schedule a phone call, or schedule a separate meeting. I am here to help, so please do not hesitate to reach out to me. (But please be respectful of my time!)
-   **HAVE FUN!** Public administration/policy is a broad topic that explores big, important questions that affect everyone. Discussing these topics should be as fun and interesting as it is challenging.
-   The table below lays out the grading scale that will be used in assigning final course grades.
-   Students with special physical and/or learning needs will be accommodated. Please notify the Disabilities Office and me as soon as possible so that reasonable accommodations can be made.

::: callout-important
**NOTE:** Throughout the semester, I may add or subtract readings as needed to adjust the course according to your progress, engagement, and interests.
:::

Table. Grade Scale Used for Calculating Class Grades

| Percent | Grade | Points |
|:-------:|:-----:|:------:|
| 93-100  |   A   |  4.0   |
|  90-92  |  A-   |  3.7   |
|  87-89  |  B+   |  3.3   |
|  83-86  |   B   |  3.0   |
|  80-82  |  B-   |  2.7   |
|  77-79  |  C+   |  2.3   |
|  73-76  |   C   |  2.0   |
|  70-72  |  C-   |  1.7   |
|  67-69  |  D+   |  1.3   |
|  63-66  |   D   |  1.0   |
|  60-62  |  D-   |  0.7   |
|  \< 60  |   F   |  0.0   |

::: callout-note
**Note:** the percent refers to the percent of available weighted points earned. Each assignment is weighted by the proportion of the final grade made up by the assignment itself, as described above.
:::

### Academic integrity

Academic honesty is something your professor takes very seriously. Cheating in any form will not be tolerated. Students are required to be familiar with the university's academic honesty policies; ignorance is not an excuse for dishonest behavior. In all cases of cheating, a Violation of Academic Integrity Report will be submitted to the Dean of Graduate Studies to be placed in your university file, with copies provided to you, the department head, and the Dean of Rockefeller College. Additional penalties may include some combination of the following: revision and re-submission of the assignment, reduction of the grade or failure of the assignment, reduction of the course grade or failure of the course, filing of a case with the Office of Conflict Resolution and Civic Responsibility, suspension, or expulsion. For a more detailed description of the university's academic honesty policies, visit the [site](http://www.albany.edu/graduatebulletin/requirements_degree.htm#standards_integrity).

### Students with Disabilities

We are committed to providing an accessible learning environment for all students. This includes students with physical, sensory, medical, cognitive, learning, mental health, and other disabilities. If you have, or think you may have a disability, please contact Disability Access and Inclusion Student Services (DAISS) by emailing daiss\@albany.edu or calling 518 -442-5501. DAISS staff will explain the documentation and registration process, and set you up with an appointment. Once you have completed registration, you will be provided with a letter to inform your instructors that you are a student with a disability registered with DAISS, and which lists the recommended reasonable accommodations for your courses.

### Counseling Center

The Counseling Center (518-442-5800; 400 Patroon Creek Blvd, Suite 104) offers counseling and consultations regarding personal concerns, self-help information, and connections to off-campus resources. More information can be found at their [site](http://www.albany.edu/counseling_center/index.shtml).

### Library Assistance

SUNY-Albany offers a great collection available in several different media. Access to research help and library tutorials can be found online at the [library's site](http://library.albany.edu/).

For information about SUNY-Albany's Dewey Graduate Library, which is located on the Downtown Campus, visit their [site](http://library.albany.edu/dewey?source=drop).

### Writing Center

The university offers a number of services for students who need assistance with writing and research projects. Support is available in the Writing Center (518-442-4061; 140 HU) and at the University Library. Information about the Writing Center can be found at their [site](http://www.albany.edu/writing/index.html).

### Title IX and Sexual Violence Prevention

Title IX of the Education Amendments of 1972 is a federal civil rights law that prohibits discrimination on the basis of sex in federally funded education programs and activities. The SUNY-wide Sexual Violence Prevention and Response Policies prohibit offenses defined as sexual harassment, sexual assault, intimate partner violence (dating or domestic violence), sexual exploitation, and stalking. The SUNY-wide Sexual Violence Prevention and Response Policies apply to the entire University at Albany community, including students, faculty, and staff of all gender identities. The University at Albany provides a variety of resources for support and advocacy to assist individuals who have experienced sexual offenses.

Confidential support and guidance can be found through the Counseling Center (518-442-5800, [or online](https://www.albany.edu/counseling_center/)), the University Health Center (518-442-5454, [or online](https://www.albany.edu/health_center/)), and the Interfaith Center (518-489-8573, [or online](https://www.albany.edu/spirituality/onCampus.shtml)). Individuals at these locations will not report crimes to law enforcement or university officials without permission, except for in extreme circumstances, such as a health and/or safety emergency. Additionally, the Advocates at the University at Albany's Advocacy Center for Sexual Violence are available to assist students without sharing information that could identify them (518-442-CARE, [or online](https://www.albany.edu/advocacycenter/)).

Sexual offenses can be reported non-confidentially to the Title IX Coordinator within The Office for Equity and Compliance (518-442-3800, [or online](https://www.albany.edu/equity-compliance/), Building 25, Room 117) and/or the University Police Department (518-442-3131, [or online](http://police.albany.edu/)).

::: callout-important
**PLEASE NOTE:** Faculty members are considered "responsible employees" at the University at Albany, meaning that they are required to report all known relevant details about a complaint of sexual violence to the University's Title IX Coordinator, including names of anyone involved or present, date, time, and location.
:::

In case of an emergency, please call 911.

### Incomplete Grade Policy

A tentative grade given only when the student has nearly completed the course but due to circumstances beyond the student's control the work is not completed on schedule. The date for the completion of the work is specified by the instructor. The date stipulated will not be later than one month before the end of the session following that in which the Incomplete is received. The grade I is automatically changed to E or U unless work is completed as agreed between the student and the instructor.

### Absence due to religious observance

Students are excused, without penalty, to be absent because of religious beliefs, and will be provided equivalent opportunities for make-up examinations, study, or work requirements missed because of such absences. Students should notify the instructor of record in a timely manner, and the instructor will work directly with students to accommodate religious observances. Online courses will not schedule any assignment deadlines on religious holidays.

## Appendix

### NASPAA Competencies

### Competency 1: The ability to lead and manage in public governance

An MPA graduate from Rockefeller College will be able to energize people and resources in the pursuit of publically defined policy goals in a manner that respects multiple perspectives and recognizes consequences of their actions.

Within organizations, our MPA graduates will:

-   Demonstrate leadership in personal work and group settings.
-   Prioritize activities in a manner consistent with organizational strategy and performance goals, regardless of their position in the hierarchy.
-   Facilitate, plan, and manage projects to meet organizational goals.

To those outside of their organizations, our MPA graduates will:

-   Display responsible stewardship of public resources and accountability to the public interest.
-   Coordinate actions with multiple organizations.
-   Navigate the competing interests of other governmental and non-governmental actors.

### Competency 2: To participate in and contribute to the policy process

An MPA graduate from Rockefeller College will substantively participate in the design, implementation, and evaluation of public policy. An MPA graduate will be able to:

-   Formulate policy objectives and priorities that are consistent with their organization's mission.
-   Facilitate change by developing new insights, questioning conventional approaches, and encouraging novel ideas and innovations within legal, political, and institutional constraints.
-   Participate in the development of networks spanning organizational boundaries to build strategic relationships to achieve common goals.
-   Evaluate whether public, private, or non-profit sectors may be more effective in achieving policy goals.
-   Balance: o Conflicting and interdependent interests of multiple constituencies. o Program performance, legal requirements, political constraints, and equity concerns when evaluating policy.

### Competency 3: To analyze, synthesize, think critically, solve problems and make decisions

An MPA graduate from Rockefeller College will substantively contribute to evidence-based decision making that appropriately analyzes information and recognizes stakeholders' competing values. This is achieved by:

-   Analyzing information to define and evaluate program performance by: o Breaking complex problems into constituent parts. o Assessing relevance, bias, and accuracy of information. o Comparing information from multiple sources o Organizing information using appropriate quantitative and/or qualitative methodologies to identify meaningful patterns.
-   Identifying potential solutions to problems by: o Differentiating between short- and long-term problems and solutions. o Evaluating policy options in light of competing political interests, organizational priorities, equity; and efficiency. o Making decisions in the face of limited information, ambiguity, and time constraints.
-   Communicating recommendations in a manner that: o Articulates actionable recommendations. o Assesses the significance of problems and solutions. o Prioritizes proposals. o Explains positive and negative implications of options. o Provides well-documented analysis that will stand up to public scrutiny.

### Competency 4: To articulate and apply a public service perspective

An MPA graduate from Rockefeller College is motivated by a sense of responsibility to improve social welfare. An MPA graduate will:

-   Articulate what it means to promote principles of equity, representativeness, responsiveness, transparency, and fair process in protecting citizens' rights.
-   Demonstrate these values in their interactions with diverse constituencies.
-   Describe tradeoffs of implementing public policies through the public, private, and/or non-profit sectors.
-   Act in a manner that: o Demonstrates a sense of duty, ethics, and integrity. o Minimizes conflicts of interest o Builds public trust.

### Competency 5: To communicate and interact productively with a diverse and changing workforce and citizenry

An MPA graduate from Rockefeller College will professionally represent their organization's interests to stakeholders by:

-   Presenting information, in writing and orally, that is concise, accurate, clear, and informed by evidence.
-   Tailoring information to diverse audiences.
-   Facilitating involvement and cooperation, building consensus, and motivating stakeholders to accomplish shared policy goals.
-   Seeking out, considering, and incorporating diverse perspectives.
-   Demonstrating courtesy, sensitivity, and respect when interacting with diverse audiences.
